# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.generate_parenthesis as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    var_0 = module_0.generate_parenthesis_v1(bool_0)
    module_0.generate_parenthesis_v1(var_0)


def test_case_1():
    int_0 = -2381
    var_0 = module_0.generate_parenthesis_v1(int_0)
    var_1 = module_0.generate_parenthesis_v1(int_0)
    var_2 = module_0.generate_parenthesis_v1(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    bool_0 = True
    var_0 = module_0.generate_parenthesis_v2(bool_0)
    module_0.generate_parenthesis_v2(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.generate_parenthesis_v2(none_type_0)


def test_case_4():
    pass


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 12345
    module_0.generate_parenthesis_v1(int_0)
