# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.limit as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    set_0 = set()
    var_0 = module_0.limit(set_0, set_0)
    bytes_0 = b"\x9b\x82\xf6\x0eBi\x81\xc5K:\x84)Hq:A\x12L\xed\xb8"
    var_1 = module_0.limit(bytes_0)
    module_0.limit(bytes_0, bytes_0, bytes_0)


def test_case_1():
    bytes_0 = b"\xe9T\x9b\x12/\xc8>\x90\xbb\xa6\xc4@1\xb9"
    var_0 = module_0.limit(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.limit(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"*+\xac'z\x10\nh\x9e]"
    var_0 = module_0.limit(bytes_0)
    module_0.limit(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b"\xe9T\x9b\x12/\xc8>\x90\xbb\xa6\xc4@1\xb9"
    module_0.limit(bytes_0, max_lim=bytes_0)


def test_case_5():
    str_0 = ".Z~a8N5u0%ou3<"
    var_0 = module_0.limit(str_0, str_0, str_0)
