# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.swap_pair as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    module_0.swap_pair(dict_0)
