# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.single_number as module_0


def test_case_0():
    set_0 = set()
    var_0 = module_0.single_number(set_0)
    assert var_0 == 0
    tuple_0 = (var_0, var_0, var_0)
    var_1 = module_0.single_number(tuple_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.single_number(list_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.single_number(bool_0)
