# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.subsets as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    int_0 = 4868
    tuple_0 = (bool_0, bool_0, int_0)
    var_0 = module_0.subsets(tuple_0)
    object_0 = module_1.object()
    module_0.subsets(object_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.subsets(bool_0)
