# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.distribution.histogram as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -2337
    dict_0 = {}
    tuple_0 = (int_0, dict_0)
    module_0.get_histogram(tuple_0)


def test_case_1():
    list_0 = []
    dict_0 = module_0.get_histogram(list_0)
