# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.count_ones as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.count_ones_iter(bool_0)
    assert var_0 == 1
    var_1 = module_0.count_ones_iter(var_0)
    assert var_1 == 1
    var_2 = module_0.count_ones_recur(var_0)
    assert var_2 == 1


def test_case_1():
    list_0 = []
    var_0 = module_0.count_ones_recur(list_0)
    assert var_0 == 0
    var_1 = module_0.count_ones_iter(list_0)
    assert var_1 == 0


def test_case_2():
    int_0 = 471
    var_0 = module_0.count_ones_iter(int_0)
    assert var_0 == 7


def test_case_3():
    none_type_0 = None
    var_0 = module_0.count_ones_iter(none_type_0)
    assert var_0 == 0
