# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.max_ones_index as module_0


def test_case_0():
    bytes_0 = b"K\t\xe4a\x17e\x1c\x18LS\xd3n"
    var_0 = module_0.max_ones_index(bytes_0)
    assert var_0 == -1


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    tuple_0 = (bool_0, bool_0, bool_0, bool_0)
    var_0 = module_0.max_ones_index(tuple_0)
    assert var_0 == 0
    module_0.max_ones_index(var_0)
