# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dfs.pacific_atlantic as module_0


def test_case_0():
    bytes_0 = b"\x9e"
    list_0 = [bytes_0]
    var_0 = module_0.pacific_atlantic(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    set_0 = set()
    var_0 = module_0.pacific_atlantic(set_0)
    complex_0 = 1722.8 + 337.255j
    module_0.pacific_atlantic(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.dfs(none_type_0, none_type_0, none_type_0, none_type_0, none_type_0)


def test_case_3():
    bytes_0 = b"\x1e\x9e"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.pacific_atlantic(list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    set_0 = set()
    list_0 = [set_0, set_0, set_0]
    var_0 = module_0.pacific_atlantic(list_0)
    bool_0 = False
    module_0.pacific_atlantic(bool_0)
