# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.letter_combination as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.letter_combinations(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = 'D"E'
    module_0.letter_combinations(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = '"\\H0A7%\\?I;B'
    list_0 = []
    var_0 = module_0.letter_combinations(list_0)
    list_1 = [str_0, str_0]
    module_0.letter_combinations(list_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "36rkq\r"
    module_0.letter_combinations(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = ""
    var_0 = module_0.letter_combinations(str_0)
    str_1 = "36rk5\r"
    module_0.letter_combinations(str_1)
