# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.single_number2 as module_0


def test_case_0():
    bytes_0 = b"\xd3\x83]\xbcw\xa4\x00\xd6\xf5\x19G\x16FkN\tOj\xa6"
    var_0 = module_0.single_number2(bytes_0)
    assert var_0 == 161
    var_1 = module_0.single_number2(bytes_0)
    assert var_1 == 161
