# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.find_missing_number as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "5p$2`3a5&l:\x0bv1"
    module_0.find_missing_number(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1522
    list_0 = [int_0, int_0, int_0, int_0]
    var_0 = module_0.find_missing_number2(list_0)
    assert var_0 == -6078
    tuple_0 = (var_0,)
    var_1 = module_0.find_missing_number(tuple_0)
    assert var_1 == -6077
    module_0.find_missing_number(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.find_missing_number2(none_type_0)
