# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.remove_bit as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 193.0259
    module_0.remove_bit(float_0, float_0)
