# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.graph.find_all_cliques as module_0


def test_case_0():
    str_0 = "\nFirst solution: Horizontal scanning\n"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.find_all_cliques(dict_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.find_all_cliques(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.find_all_cliques(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "b"
    str_1 = "btq.:yiP)(=+"
    dict_0 = {str_0: str_0, str_0: str_0, str_1: str_1}
    var_0 = module_0.find_all_cliques(dict_0)
    module_0.find_all_cliques(var_0)
