# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.word_break as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.word_break(bool_0, bool_0)


def test_case_1():
    bytes_0 = b"\x13b\xc23+\x1b\x9e\xf9\xfez"
    var_0 = module_0.word_break(bytes_0, bytes_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"@G\xbdx\ngn\xaa\xb0\xc6\r\xacv\x8dD\xca\xf3#\x94"
    bytes_1 = b"\x01,\xef+\x02 ,\xf6g\xddfm\xb5\xf1"
    tuple_0 = (bytes_0, bytes_1)
    var_0 = module_0.word_break(tuple_0, tuple_0)
    assert var_0 is False
    bool_0 = True
    module_0.word_break(bool_0, bool_0)
