# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.buy_sell_stock as module_0


def test_case_0():
    bytes_0 = b"\x8b\xa7R\x94\xd2n \xa4"
    var_0 = module_0.max_profit_naive(bytes_0)
    assert var_0 == 132


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    var_0 = module_0.max_profit_naive(list_0)
    assert var_0 == 0
    str_0 = "bsR"
    module_0.max_profit_optimized(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    var_0 = module_0.max_profit_optimized(set_0)
    assert var_0 == 0
    module_0.max_profit_optimized(var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.max_profit_naive(none_type_0)
