# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.plus_one as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "}7q1OoU9cWD-y*'b?pvH"
    module_0.plus_one_v2(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "\\"
    module_0.plus_one_v3(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    module_0.plus_one_v3(set_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "\\D"
    module_0.plus_one_v1(str_0)


def test_case_4():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.plus_one_v2(list_0)
    var_1 = module_0.plus_one_v1(var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.plus_one_v3(list_0)
    module_0.plus_one_v2(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bytes_0 = b"\xe7g\xd7\xcfd\x18"
    module_0.plus_one_v2(bytes_0)


def test_case_7():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.plus_one_v1(list_0)


def test_case_8():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.plus_one_v2(list_0)
    var_1 = module_0.plus_one_v3(var_0)
    var_2 = module_0.plus_one_v2(var_1)
    var_3 = module_0.plus_one_v2(list_0)
    var_4 = module_0.plus_one_v2(list_0)
    var_5 = module_0.plus_one_v2(var_4)
    var_6 = module_0.plus_one_v3(var_2)
    var_7 = module_0.plus_one_v3(var_1)
    var_8 = module_0.plus_one_v2(var_7)
    var_9 = module_0.plus_one_v3(var_8)
    var_10 = module_0.plus_one_v1(var_9)


@pytest.mark.xfail(strict=True)
def test_case_9():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.plus_one_v2(list_0)
    var_1 = module_0.plus_one_v3(list_0)
    var_2 = module_0.plus_one_v2(var_1)
    var_3 = module_0.plus_one_v1(var_2)
    var_4 = module_0.plus_one_v2(list_0)
    var_5 = module_0.plus_one_v2(list_0)
    float_0 = 3193.0
    var_6 = module_0.plus_one_v2(var_5)
    var_7 = module_0.plus_one_v3(var_2)
    var_8 = module_0.plus_one_v2(var_6)
    var_9 = module_0.plus_one_v1(list_0)
    module_0.plus_one_v1(float_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.plus_one_v1(list_0)
    var_1 = module_0.plus_one_v2(list_0)
    var_2 = module_0.plus_one_v3(var_1)
    var_3 = module_0.plus_one_v3(var_0)
    var_4 = module_0.plus_one_v2(var_3)
    var_5 = module_0.plus_one_v2(var_0)
    set_0 = set()
    module_0.plus_one_v2(set_0)
