# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.trimmean as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.trimmean(bool_0, bool_0)


def test_case_1():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0]
    bool_1 = True
    var_0 = module_0.trimmean(list_0, bool_1)
    assert var_0 == pytest.approx(1.0, abs=0.01, rel=0.01)
