# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.subsets_unique as module_0


def test_case_0():
    set_0 = set()
    var_0 = module_0.subsets_unique(set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "2"
    set_0 = {str_0, str_0}
    module_0.subsets_unique(set_0)
