# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.bit_operation as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    module_0.set_bit(list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    set_0 = set()
    module_0.get_bit(set_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.clear_bit(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.update_bit(none_type_0, none_type_0, none_type_0)
