# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.min_cost_path as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    set_0 = set()
    module_0.min_cost(set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b".\xc1v\x1d\xd2\x94q\x02"
    module_0.min_cost(bytes_0)


def test_case_2():
    bytes_0 = b"\xf1"
    var_0 = module_0.min_cost(bytes_0)
    assert var_0 == 0
