# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.garage as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"$\rH\xee0F\x7fH\xce\x99\t\xa6\xb1g"
    var_0 = module_0.garage(bytes_0, bytes_0)
    module_0.garage(var_0, bytes_0)


def test_case_1():
    bytes_0 = b"$\rH\xee0F\x7fH\xce\x99\t\xa6\xb1g"
    var_0 = module_0.garage(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    object_0 = module_1.object()
    module_0.garage(object_0, object_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    tuple_0 = (bool_0, bool_0, bool_0, bool_0)
    var_0 = module_0.garage(tuple_0, tuple_0)
    var_1 = module_0.garage(var_0, var_0)
    var_2 = module_0.garage(var_0, var_0)
    var_3 = module_0.garage(var_0, var_0)
    list_0 = [bool_0, var_3, var_2, tuple_0]
    module_0.garage(list_0, var_3)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    tuple_0 = (bool_0, bool_0, bool_0, bool_0)
    var_0 = module_0.garage(tuple_0, tuple_0)
    module_0.garage(var_0, tuple_0)
