# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.longest_common_subsequence as module_0


def test_case_0():
    str_0 = "\nGiven an array of integers nums sorted in ascending order, find the starting\nand ending position of a given target value. If the target is not found in the\narray, return [-1, -1].\n\nFor example:\nInput: nums = [5,7,7,8,8,8,10], target = 8\nOutput: [3,5]\nInput: nums = [5,7,7,8,8,8,10], target = 11\nOutput: [-1,-1]\n"
    var_0 = module_0.longest_common_subsequence(str_0, str_0)
    assert var_0 == 312


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.longest_common_subsequence(bool_0, bool_0)
