# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.find_difference as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 1206
    list_0 = [int_0]
    module_0.find_difference(list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ";3Q2=5vhU8<sJO@J"
    var_0 = module_0.find_difference(str_0, str_0)
    assert var_0 == "\x00"
    bool_0 = False
    module_0.find_difference(var_0, bool_0)
