# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import builtins as module_0
import algorithms.backtrack.subsets as module_1


def test_case_0():
    object_0 = module_0.object()
    list_0 = [object_0, object_0, object_0]
    bytes_0 = b"r\xdeR\xc5E"
    list_1 = [list_0, bytes_0]
    var_0 = module_1.subsets(list_1)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -2674
    list_0 = [int_0, int_0, int_0]
    var_0 = module_1.subsets_v2(list_0)
    float_0 = 0.0
    module_1.subsets_v2(float_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "q#Gq3"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    module_0.object(**dict_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_1.subsets(none_type_0)
