# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.single_number3 as module_0
import builtins as module_1


def test_case_0():
    int_0 = -1815
    dict_0 = {int_0: int_0, int_0: int_0}
    var_0 = module_0.single_number3(dict_0)
    var_1 = module_0.single_number3(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    object_0 = module_1.object()
    module_0.single_number3(object_0)
