# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.josephus as module_0
import builtins as module_1


def test_case_0():
    int_0 = 97
    var_0 = module_0.josephus(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1024
    bytes_0 = b"y"
    var_0 = module_0.josephus(bytes_0, int_0)
    module_1.object(*var_0)


def test_case_2():
    int_0 = 1024
    bytes_0 = b""
    var_0 = module_0.josephus(bytes_0, int_0)
    object_0 = module_1.object(*var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 1021
    bytes_0 = b"S"
    bool_0 = True
    list_0 = [bytes_0, int_0, bool_0, bytes_0]
    var_0 = module_0.josephus(list_0, int_0)
    module_1.object(*var_0)
