# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.add_bitwise_operator as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.add_bitwise_operator(bool_0, bool_0)
    assert var_0 == 2


def test_case_1():
    set_0 = set()
    var_0 = module_0.add_bitwise_operator(set_0, set_0)
