# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.graph.clone_graph as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x81\x91E"
    module_0.clone_graph1(bytes_0)


def test_case_1():
    tuple_0 = ()
    undirected_graph_node_0 = module_0.clone_graph1(tuple_0)
    var_0 = module_0.clone_graph2(undirected_graph_node_0)


def test_case_2():
    tuple_0 = ()
    undirected_graph_node_0 = module_0.UndirectedGraphNode(tuple_0)
    var_0 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_0.label == ()
    assert var_0.neighbors == []


def test_case_3():
    bool_0 = False
    undirected_graph_node_0 = module_0.UndirectedGraphNode(bool_0)
    var_0 = module_0.clone_graph1(undirected_graph_node_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_0.label is False
    assert var_0.neighbors == []
    var_1 = module_0.clone_graph(var_0)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_1.label is False
    assert var_1.neighbors == []


def test_case_4():
    none_type_0 = None
    var_0 = module_0.clone_graph(none_type_0)


def test_case_5():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    undirected_graph_node_1 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = undirected_graph_node_1.shallow_copy()
    var_1 = undirected_graph_node_1.add_neighbor(undirected_graph_node_1)
    var_2 = module_0.clone_graph(undirected_graph_node_0)
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert var_2.neighbors == []
    var_3 = undirected_graph_node_1.shallow_copy()


def test_case_6():
    bool_0 = False
    undirected_graph_node_0 = module_0.UndirectedGraphNode(bool_0)
    var_0 = module_0.clone_graph1(undirected_graph_node_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_0.label is False
    assert var_0.neighbors == []


@pytest.mark.xfail(strict=True)
def test_case_7():
    int_0 = 1325
    undirected_graph_node_0 = module_0.UndirectedGraphNode(int_0)
    var_0 = undirected_graph_node_0.add_neighbor(int_0)
    module_0.clone_graph2(undirected_graph_node_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    int_0 = 1325
    undirected_graph_node_0 = module_0.UndirectedGraphNode(int_0)
    var_0 = undirected_graph_node_0.shallow_copy()
    var_1 = undirected_graph_node_0.add_neighbor(undirected_graph_node_0)
    var_2 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label == 1325
    assert (
        f"{type(var_2.neighbors).__module__}.{type(var_2.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_2.neighbors) == 1
    var_3 = module_0.clone_graph(var_2)
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_3.label == 1325
    assert (
        f"{type(var_3.neighbors).__module__}.{type(var_3.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_3.neighbors) == 1
    var_2.isnumeric()


@pytest.mark.xfail(strict=True)
def test_case_9():
    int_0 = 1325
    none_type_0 = None
    var_0 = module_0.clone_graph1(none_type_0)
    undirected_graph_node_0 = module_0.UndirectedGraphNode(int_0)
    var_1 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_1.label == 1325
    assert var_1.neighbors == []
    var_2 = var_1.add_neighbor(var_0)
    assert var_1.neighbors == [None]
    module_0.clone_graph1(var_1)


@pytest.mark.xfail(strict=True)
def test_case_10():
    none_type_0 = None
    var_0 = module_0.clone_graph1(none_type_0)
    undirected_graph_node_0 = module_0.UndirectedGraphNode(var_0)
    var_1 = undirected_graph_node_0.add_neighbor(undirected_graph_node_0)
    var_2 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert (
        f"{type(var_2.neighbors).__module__}.{type(var_2.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_2.neighbors) == 1
    var_3 = module_0.clone_graph1(var_2)
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_3.label is None
    assert (
        f"{type(var_3.neighbors).__module__}.{type(var_3.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_3.neighbors) == 1
    var_4 = module_0.clone_graph(var_2)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_4.label is None
    assert (
        f"{type(var_4.neighbors).__module__}.{type(var_4.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_4.neighbors) == 1
    undirected_graph_node_1 = module_0.UndirectedGraphNode(var_0)
    var_3.rsplit()


@pytest.mark.xfail(strict=True)
def test_case_11():
    none_type_0 = None
    var_0 = module_0.clone_graph1(none_type_0)
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_1 = undirected_graph_node_0.add_neighbor(none_type_0)
    var_2 = module_0.clone_graph2(var_1)
    var_3 = module_0.clone_graph1(none_type_0)
    module_0.clone_graph(undirected_graph_node_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    none_type_0 = None
    var_0 = module_0.clone_graph1(none_type_0)
    undirected_graph_node_0 = module_0.UndirectedGraphNode(var_0)
    var_1 = undirected_graph_node_0.shallow_copy()
    var_2 = undirected_graph_node_0.add_neighbor(var_1)
    var_3 = undirected_graph_node_0.add_neighbor(undirected_graph_node_0)
    var_4 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_4.label is None
    assert (
        f"{type(var_4.neighbors).__module__}.{type(var_4.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_4.neighbors) == 2
    var_5 = module_0.clone_graph1(var_4)
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_5.label is None
    assert (
        f"{type(var_5.neighbors).__module__}.{type(var_5.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_5.neighbors) == 2
    var_6 = module_0.clone_graph(var_4)
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_6.label is None
    assert (
        f"{type(var_6.neighbors).__module__}.{type(var_6.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_6.neighbors) == 2
    undirected_graph_node_1 = module_0.UndirectedGraphNode(var_0)
    var_5.rsplit()
