# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.edit_distance as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "7:(iI"
    var_0 = module_0.edit_distance(str_0, str_0)
    assert var_0 == 0
    module_0.edit_distance(var_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    complex_0 = 4450.82488 + 884.709j
    module_0.edit_distance(complex_0, complex_0)
