# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dfs.count_islands as module_0


def test_case_0():
    str_0 = "-bwSY"
    var_0 = module_0.num_islands(str_0)
    assert var_0 == 0
    var_1 = module_0.dfs(str_0, var_0, var_0)
    var_2 = module_0.num_islands(str_0)
    assert var_2 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    set_0 = set()
    var_0 = module_0.num_islands(set_0)
    assert var_0 == 0
    list_0 = []
    module_0.dfs(set_0, list_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.dfs(bool_0, bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    set_0 = set()
    var_0 = module_0.num_islands(set_0)
    assert var_0 == 0
    var_1 = module_0.dfs(set_0, var_0, var_0)
    module_0.num_islands(var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = 'C"[7e\x0cANP!FEr} %'
    bool_0 = True
    tuple_0 = (bool_0, bool_0)
    tuple_1 = (str_0, tuple_0, bool_0)
    module_0.num_islands(tuple_1)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = 'C"[7e\x0cANP!FEr} %'
    int_0 = -794
    var_0 = module_0.dfs(int_0, int_0, str_0)
    bool_0 = True
    tuple_0 = (bool_0, bool_0)
    tuple_1 = (str_0, tuple_0, bool_0)
    module_0.num_islands(tuple_1)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = 'C"[7e\x0cANP!FEr} %'
    bool_0 = True
    tuple_0 = module_0.dfs(str_0, bool_0, bool_0)
    tuple_1 = (str_0, tuple_0, bool_0)
    module_0.num_islands(tuple_1)


@pytest.mark.xfail(strict=True)
def test_case_7():
    int_0 = -794
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    tuple_1 = module_0.dfs(tuple_0, bool_0, int_0)
    set_0 = set()
    var_0 = module_0.num_islands(set_0)
    assert var_0 == 0
    bool_1 = False
    var_1 = module_0.dfs(set_0, bool_1, set_0)
    module_0.num_islands(bool_1)
