# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.merge_intervals as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.as_list()
    var_1 = var_0.__len__()
    assert var_1 == 0
    var_2 = interval_0.__contains__(var_1)
    assert var_2 is True
    module_0.merge_intervals(var_0)


def test_case_1():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__iter__()
    var_1 = interval_0.print_intervals(var_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.merge_intervals(none_type_0)
    interval_0 = module_0.Interval(end=var_0)
    assert interval_0.start == 0


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = -2218.017720598655
    module_0.merge_intervals(float_0)


def test_case_4():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0


def test_case_5():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__repr__()
    assert var_0 == "Interval (0, 0)"
    var_1 = interval_0.__eq__(interval_0)
    assert var_1 is True
    var_2 = interval_0.as_list()


def test_case_6():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__iter__()
    var_1 = interval_0.merge(var_0)


def test_case_7():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__eq__(interval_0)
    assert var_0 is True
    var_1 = interval_0.as_list()


def test_case_8():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    list_0 = [interval_0, interval_0, interval_0]
    var_0 = interval_0.merge(list_0)


def test_case_9():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__len__()
    assert var_0 == 0
    list_0 = [interval_0, interval_0, interval_0]
    var_1 = interval_0.merge(list_0)
    var_2 = var_1.__len__()
    assert var_2 == 1
    var_3 = interval_0.__contains__(var_2)
    assert var_3 is False
    var_4 = module_0.merge_intervals(var_1)
    var_5 = var_1.__iter__()


def test_case_10():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__eq__(interval_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_11():
    str_0 = "#!ura9Kcc.j"
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.print_intervals(str_0)
    module_0.merge_intervals(str_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    str_0 = "t"
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__repr__()
    assert var_0 == "Interval (0, 0)"
    list_0 = [str_0, str_0]
    module_0.merge_intervals(list_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__repr__()
    assert var_0 == "Interval (0, 0)"
    var_1 = interval_0.merge(interval_0)
    var_2 = interval_0.__eq__(interval_0)
    assert var_2 is True
    var_3 = interval_0.as_list()
    var_4 = interval_0.as_list()
    var_5 = interval_0.__contains__(var_2)
    assert var_5 is False
    interval_1 = module_0.Interval(end=var_1)
    var_3.__getitem__(var_2)


def test_case_14():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    var_0 = interval_0.__len__()
    assert var_0 == 0
    list_0 = [interval_0, interval_0, interval_0]
    var_1 = interval_0.merge(list_0)
    var_2 = var_1.__repr__()
    assert var_2 == "[Interval (0, 0)]"
    var_3 = var_1.__len__()
    assert var_3 == 1
    var_4 = interval_0.__contains__(var_3)
    assert var_4 is False
    var_5 = module_0.merge_intervals(list_0)
    var_6 = module_0.merge_intervals(var_5)
    var_7 = interval_0.__iter__()


@pytest.mark.xfail(strict=True)
def test_case_15():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    interval_1 = module_0.Interval()
    assert len(interval_1) == 0
    var_0 = interval_1.merge(interval_0)
    var_1 = interval_0.print_intervals(interval_1)
    none_type_0 = None
    interval_2 = module_0.Interval(end=none_type_0)
    var_2 = interval_2.__eq__(interval_1)
    assert var_2 is False
    var_2.as_list()


@pytest.mark.xfail(strict=True)
def test_case_16():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    interval_1 = module_0.Interval()
    assert len(interval_1) == 0
    var_0 = interval_0.__eq__(interval_0)
    assert var_0 is True
    interval_2 = module_0.Interval(var_0, var_0)
    assert len(interval_2) == 0
    var_1 = interval_2.merge(interval_1)
    var_2 = interval_2.__eq__(interval_0)
    var_3 = interval_0.__len__()
    var_0.__len__()


@pytest.mark.xfail(strict=True)
def test_case_17():
    interval_0 = module_0.Interval()
    assert len(interval_0) == 0
    none_type_0 = None
    var_0 = module_0.merge_intervals(none_type_0)
    interval_1 = module_0.Interval()
    assert len(interval_1) == 0
    var_1 = interval_0.merge(interval_0)
    float_0 = -2129.07
    var_2 = interval_0.__contains__(float_0)
    assert var_2 is False
    none_type_1 = None
    var_3 = module_0.merge_intervals(var_0)
    var_4 = interval_1.__iter__()
    var_5 = module_0.merge_intervals(none_type_0)
    var_4.__getitem__(none_type_1)
