# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.anagram as module_0


def test_case_0():
    dict_0 = {}
    var_0 = module_0.anagram(dict_0, dict_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x10\xa8\n\xfb\xce/\xcb\x9e\xcc\xb3I\xa1\xbb\xde\xab9\x0c"
    module_0.anagram(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    dict_0 = {}
    tuple_0 = (dict_0,)
    module_0.anagram(dict_0, tuple_0)
