# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bfs.count_islands as module_0
import builtins as module_1


def test_case_0():
    bytes_0 = b")\xd5\x08\xf9\x1d\xf2k\xde\xaf\x9c58\x01\x87mu\xb6\xf2\xc7o"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.count_islands(list_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    object_0 = module_1.object(**dict_0)
    module_0.count_islands(object_0)


def test_case_2():
    bytes_0 = b"\x01"
    list_0 = [
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
        bytes_0,
    ]
    var_0 = module_0.count_islands(list_0)
    assert var_0 == 1


def test_case_3():
    bytes_0 = b"q\xbc\xcf\x17\x02Y\x88\xa5\xa6`)UE\x01"
    list_0 = [bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, bytes_0]
    var_0 = module_0.count_islands(list_0)
    assert var_0 == 1
