# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.factor_combinations as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "~'\x0b3o\r"
    module_0.get_factors(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 63
    var_0 = module_0.recursive_get_factors(int_0)
    var_1 = module_1.object()
    module_0.get_factors(var_1)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    var_0 = module_0.recursive_get_factors(bool_0)
    var_1 = module_0.get_factors(bool_0)
    module_0.get_factors(var_1)


def test_case_3():
    float_0 = 9.231991081771639
    var_0 = module_0.get_factors(float_0)


def test_case_4():
    bool_0 = False
    var_0 = module_0.get_factors(bool_0)


def test_case_5():
    int_0 = 63
    var_0 = module_0.get_factors(int_0)
