# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.permute_unique as module_0


def test_case_0():
    bytes_0 = b"\xf1\xd7\xed5(-\x83aS\xcf"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    var_0 = module_0.permute_unique(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    float_0 = 0.1
    module_0.permute_unique(float_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    bytes_0 = b"o\xf0\xb5\n\xd9\x05\xceRM\xbc<"
    list_0 = [bool_0, bool_0, bool_0, bytes_0]
    var_0 = module_0.permute_unique(list_0)
    none_type_0 = None
    module_0.permute_unique(none_type_0)
