# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.coin_change as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -50
    list_0 = [int_0, int_0, int_0, int_0]
    module_0.count(list_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.count(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -50
    bytes_0 = b"#zb$\xea\xe2c\xff\x1f\xd5N0\x84A>\xaf"
    module_0.count(bytes_0, int_0)
