# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dfs.sudoku_solver as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.Sudoku(bool_0, bool_0, bool_0)


def test_case_1():
    bool_0 = False
    sudoku_0 = module_0.Sudoku(bool_0, bool_0, bool_0)


def test_case_2():
    bool_0 = False
    sudoku_0 = module_0.Sudoku(bool_0, bool_0, bool_0)
    var_0 = sudoku_0.solve()
    assert var_0 is True


def test_case_3():
    bool_0 = False
    sudoku_0 = module_0.Sudoku(bool_0, bool_0, bool_0)
    var_0 = sudoku_0.__str__()
    assert var_0 == ""
    var_1 = sudoku_0.solve()
    assert var_1 is True


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    bool_0.possible_values()


def test_case_5():
    bool_0 = True
    str_0 = "\"R5I1)mt'r0Dn:Q8,Wes"
    sudoku_0 = module_0.Sudoku(str_0, bool_0, bool_0)
    assert (
        f"{type(sudoku_0).__module__}.{type(sudoku_0).__qualname__}"
        == "algorithms.dfs.sudoku_solver.Sudoku"
    )
    assert sudoku_0.board == "\"R5I1)mt'r0Dn:Q8,Wes"
    assert sudoku_0.row is True
    assert sudoku_0.col is True
    assert sudoku_0.val == {}


def test_case_6():
    bool_0 = True
    bool_1 = False
    sudoku_0 = module_0.Sudoku(bool_0, bool_0, bool_1)
    var_0 = sudoku_0.__str__()
    assert var_0 == "\n"
    var_1 = sudoku_0.possible_values()


@pytest.mark.xfail(strict=True)
def test_case_7():
    bool_0 = True
    str_0 = "."
    sudoku_0 = module_0.Sudoku(str_0, bool_0, bool_0)
    assert (
        f"{type(sudoku_0).__module__}.{type(sudoku_0).__qualname__}"
        == "algorithms.dfs.sudoku_solver.Sudoku"
    )
    assert sudoku_0.board == "."
    assert sudoku_0.row is True
    assert sudoku_0.col is True
    assert sudoku_0.val == {(0, 0): ["1", "2", "3", "4", "5", "6", "7", "8", "9"]}
    var_0 = sudoku_0.__str__()
    assert var_0 == " . \n"
    sudoku_0.solve()


def test_case_8():
    bool_0 = True
    str_0 = "."
    sudoku_0 = module_0.Sudoku(str_0, bool_0, bool_0)
    assert (
        f"{type(sudoku_0).__module__}.{type(sudoku_0).__qualname__}"
        == "algorithms.dfs.sudoku_solver.Sudoku"
    )
    assert sudoku_0.board == "."
    assert sudoku_0.row is True
    assert sudoku_0.col is True
    assert sudoku_0.val == {(0, 0): ["1", "2", "3", "4", "5", "6", "7", "8", "9"]}


@pytest.mark.xfail(strict=True)
def test_case_9():
    bool_0 = True
    str_0 = "."
    sudoku_0 = module_0.Sudoku(str_0, bool_0, bool_0)
    assert (
        f"{type(sudoku_0).__module__}.{type(sudoku_0).__qualname__}"
        == "algorithms.dfs.sudoku_solver.Sudoku"
    )
    assert sudoku_0.board == "."
    assert sudoku_0.row is True
    assert sudoku_0.col is True
    assert sudoku_0.val == {(0, 0): ["1", "2", "3", "4", "5", "6", "7", "8", "9"]}
    sudoku_0.solve()
