# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.reverse_bits as module_0


def test_case_0():
    int_0 = -2420
    var_0 = module_0.reverse_bits(int_0)
    assert var_0 == 829423615
