# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.two_sum as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "\nGiven two strings S and T, determine if they are both one edit distance apart.\n"
    module_0.two_sum(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 202
    dict_0 = {int_0: int_0, int_0: int_0}
    var_0 = module_0.two_sum(dict_0, int_0)
    module_0.two_sum(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0]
    var_0 = module_0.two_sum(list_0, bool_0)
    module_0.two_sum(list_0, var_0)
