# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.longest_increasing as module_0


def test_case_0():
    bytes_0 = b"\x8b\x1c\xbd\x96\xe0\xae\xd3\xf4"
    var_0 = module_0.longest_increasing_subsequence(bytes_0)
    assert var_0 == 5


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x8b\x1c\xbd\x96\xe0\xae\xd3\xf4"
    module_0.longest_increasing_subsequence_optimized(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"0\x1c\xbd\x96_\r\xd3\xf4"
    module_0.longest_increasing_subsequence_optimized2(bytes_0)


def test_case_3():
    tuple_0 = ()
    var_0 = module_0.longest_increasing_subsequence_optimized2(tuple_0)
    assert var_0 == 0


def test_case_4():
    bytes_0 = b"\xe6"
    var_0 = module_0.longest_increasing_subsequence_optimized2(bytes_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b"\x8b\x1c\xbd\x96\xe0\xae\xd3\xf4"
    module_0.longest_increasing_subsequence_optimized2(bytes_0)
