# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.matrix_chain_order as module_0


def test_case_0():
    bytes_0 = b"\xc5N\xff\xa4\xa3\xb5\x88\xcf\xeaf\xb1c\xb2\xb7"
    var_0 = module_0.print_optimal_solution(bytes_0, bytes_0, bytes_0)


def test_case_1():
    bytes_0 = b"\x16W6\xb9\xe5\xf81'\x99\x109{}"
    var_0 = module_0.matrix_chain_order(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    tuple_0 = ()
    none_type_0 = None
    module_0.print_optimal_solution(tuple_0, tuple_0, none_type_0)
