# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.min_cost_path as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "@5#P=R;6Gp3{U~o[,"
    module_0.min_cost(str_0)


def test_case_1():
    str_0 = "u"
    var_0 = module_0.min_cost(str_0)
    assert var_0 == 0
